server:
  port: 8081
spring:
  application:
    name: "Flights-Service"
  data:
    mongodb:
      host: localhost
      port: 27017
      username: flightsdbuser
      password: sa
      database: flightsdb
springdoc:
  swagger-ui:
    path: "/swagger-ui.html"
