server:
  port: 8081
spring:
  application:
    name: "Flights-Service"
  data:
    mongodb:
      host: localhost
      port: 27017
      username: flightsdbuser
      password: sa
      database: flightsdb
logging:
  level:
    root: ERROR
    org.springframework.boot.web.embedded.netty.NettyWebServer: INFO
    org.mongodb.driver.cluster: INFO
    com.mashosoft.flightsService: DEBUG
